/**
 * Curated list of major cities to pre-warm into the R2 cache.
 *
 * Two sources merge into `POPULAR_CITIES`:
 *
 *   1. The hand-curated list below in this file — small, reviewed.
 *      Edit here for cities you specifically want warmed.
 *   2. `bulk-cities.json` at the worker package root. This is the
 *      auto-discovered list (~170+ entries today) from the local
 *      discovery script. Edits there flow into the cron without
 *      any code change.
 *
 * Cron processes the merged list in random order, `PREWARM_BATCH_SIZE`
 * at a time, skipping anything that's still fresh (< CACHE_TTL_DAYS
 * old in R2). So adding a city is a one-line edit to either source.
 *
 * Entries are OSM relation IDs because that's the only thing the
 * seeker app actually fetches (no nodes, no ways — admin
 * boundaries are always relations). To add a city to the hand-list:
 * look it up on openstreetmap.org, copy the relation id from the URL
 * (e.g. `https://www.openstreetmap.org/relation/398021` -> 398021),
 * and add it here.
 *
 * Entries are best-effort — if any of these IDs are stale or
 * wrong, the worker just logs the prewarm failure and moves on;
 * the rest of the cache pipeline is unaffected.
 */

// Wrangler/esbuild bundles JSON imports as compiled-in modules
// automatically (no runtime fetch). Lives at the worker package root
// so it can be edited without touching code.
//
// `world-cities.json` is THE single canonical prewarm seed (v680) — the
// top-N biggest cities worldwide, `{name, relationId, extent?, population?}`,
// regenerated by `scripts/build-world-cities.mjs` (Wikidata population +
// OSM relation id, Photon-reconciled so the ids match in-app search). It
// replaces the old hand-curated + bulk split. The R2 growth/state doc adds
// player-picked areas + curation stamps on top (see getPopularCities).
import WORLD_CITIES from "../world-cities.json";
import BULK_CANDIDATE_NAMES from "../bulk-city-names.json";

import type { Env } from "./envTypes";

export interface CityEntry {
    name: string;
    /** OSM relation id (numeric, no prefix). */
    relationId: number;
    /** Photon's normalized bounding-box extent, lat-major:
     *  [maxLat, minLng, minLat, maxLng]. Optional because legacy
     *  entries from before v193 don't carry it; the cron lazily
     *  backfills these via a re-resolve. Used by the cron to
     *  prewarm the per-city reference caches (museums / hospitals /
     *  airports / …) with the SAME bbox the client derives from
     *  `mapGeoLocation.properties.extent`, so the R2 entries land
     *  on cache keys the client will actually hit. */
    extent?: [number, number, number, number];
    /** Unix ms at which the cron last verified that EVERY adjacent area
     *  of this city is fully curated — each neighbour's boundary,
     *  references, AND hiding-zone stations present in R2 (v676). Stamped
     *  by `prewarmAdjacentSearchForCity`'s Phase-4 caller once the
     *  verification pass passes, cleared if a neighbour regresses. Gates
     *  the star hint (`/api/warm-cities`) when `WARM_REQUIRE_ADJACENTS`
     *  is "true": the user's rule that a city can only be starred if its
     *  adjacent areas are curated too. Optional — legacy entries and
     *  islands-with-no-neighbours may lack it (a no-neighbour city stamps
     *  vacuously). */
    adjacentsCuratedAt?: number;
    /** ISO 3166-1 alpha-2 country code (uppercase), when known (v693 —
     *  from the world-cities.json seed's Wikidata P297, or the all-the-cities
     *  backfill for legacy entries). The region tag the laptop warm-order
     *  (`--priority-regions`) and any future per-country cap key off, and
     *  what makes the geographic distribution exact. Optional — a few
     *  entries whose country couldn't be resolved lack it (they warm last
     *  under a priority order). */
    country?: string;
    /** Population, when known (from the world-cities.json Wikidata seed,
     *  v680). Used only to sort the seed "biggest first"; the worker does
     *  not otherwise consume it. Optional. */
    population?: number;
    /** Unix ms at which the cron last verified this city is FULLY cached
     *  (v679) — the PRIMARY relation's boundary + references + hiding-zone
     *  stations all present in R2 AND every adjacent area curated
     *  (`adjacentsCuratedAt`). This is the single "ready to play, nothing
     *  hits Overpass" marker and the ONLY thing the in-app star reflects by
     *  default (`handleWarmCities`): a star means "fully cached, including
     *  adjacent areas". Stamped/cleared by `prewarmAdjacentSearchForCity`'s
     *  Phase-4 caller alongside `adjacentsCuratedAt`. Optional — a city is
     *  unstarred until it's earned. */
    fullyCuratedAt?: number;
    /** Unix ms at which this city's PRIMARY relation was last verified fully
     *  cached (boundary + references + hiding-zone stations all in R2) —
     *  independent of adjacent areas. This is a progress DIAGNOSTIC only
     *  (surfaced in `/admin/adjacent-curation-status` as `primaryCached`/
     *  `stampedPrimary`), NOT the star: the star is the strict
     *  `fullyCuratedAt` (primary + every adjacent), since selecting a starred
     *  city offers adding its adjacents and an un-warm adjacent would be a
     *  broken promise. Lets the operator watch "primaries done" vs "fully
     *  done" while the adjacent warming grinds through the whole seed.
     *  Stamped/cleared by `verifyAndStampCity` alongside `fullyCuratedAt`. */
    primaryCuratedAt?: number;
}

/**
 * The bundled prewarm seed (v680): the generated world-cities list, and
 * nothing else. No hand-correction/override layer — the generator
 * (`scripts/build-world-cities.mjs`) resolves each city through the app's
 * EXACT play-area ranking, so every relation id is the one in-app search
 * returns BY CONSTRUCTION. If a specific city ever resolves wrong, fix it
 * at the source (regenerate, or correct the entry in world-cities.json),
 * not with a parallel override list — that was the sprawl we removed.
 */
export const SEED_CITIES: CityEntry[] = WORLD_CITIES as CityEntry[];

/**
 * Dedupe + merge, first-wins by relationId (with field-fill: a later
 * duplicate can supply an `extent`/stamp a first-wins entry lacked, so a
 * name-authority seed entry gains runtime state without being overwritten).
 */
function mergeUnique(...lists: CityEntry[][]): CityEntry[] {
    const index = new Map<number, CityEntry>();
    const order: number[] = [];
    for (const list of lists) {
        for (const entry of list) {
            if (!entry || typeof entry.relationId !== "number") continue;
            const existing = index.get(entry.relationId);
            if (!existing) {
                index.set(entry.relationId, { ...entry });
                order.push(entry.relationId);
                continue;
            }
            // First-wins on identity/name, but FILL missing fields from
            // later duplicates — so a name-authority entry that lacks an
            // `extent`/stamp gains it from a later copy that has one
            // (fixes the old "extentless seed shadows an extent-bearing
            // duplicate" bug). Never overwrites a value the winner already
            // has.
            if (existing.extent === undefined && entry.extent !== undefined) {
                existing.extent = entry.extent;
            }
            if (existing.country === undefined && entry.country !== undefined) {
                existing.country = entry.country;
            }
            // v694 fix: fill population too. Without this, a growth-doc entry
            // (player-added / discovered — no population) that shadows a seed
            // city dropped the seed's population, so the laptop warm-order
            // (--priority-regions, --seed-first) sorted it as pop -1 and
            // warmed it LAST within its tier (NYC after Manhattan).
            if (
                existing.population === undefined &&
                entry.population !== undefined
            ) {
                existing.population = entry.population;
            }
            if (
                existing.adjacentsCuratedAt === undefined &&
                entry.adjacentsCuratedAt !== undefined
            ) {
                existing.adjacentsCuratedAt = entry.adjacentsCuratedAt;
            }
            if (
                existing.fullyCuratedAt === undefined &&
                entry.fullyCuratedAt !== undefined
            ) {
                existing.fullyCuratedAt = entry.fullyCuratedAt;
            }
            if (
                existing.primaryCuratedAt === undefined &&
                entry.primaryCuratedAt !== undefined
            ) {
                existing.primaryCuratedAt = entry.primaryCuratedAt;
            }
        }
    }
    return order.map((id) => index.get(id)!);
}

/**
 * Bundled list as a synchronous baseline. The cron / trigger /
 * discover paths prefer `getPopularCities(env)` which folds in the R2
 * growth/state doc too — but this constant stays for any caller that
 * doesn't have an Env handy.
 */
export const POPULAR_CITIES: CityEntry[] = mergeUnique(SEED_CITIES);

/** R2 key under which discovered (Photon-resolved) cities accumulate. */
export const DISCOVERED_R2_KEY = "_meta/discovered-cities.json";

/**
 * Same merge as `POPULAR_CITIES`, plus anything the
 * `/admin/discover` endpoint or the cron's discovery pass has
 * resolved and stored in R2. Cached at module scope so repeat calls
 * inside the same worker invocation don't re-hit R2.
 */
let _discoveredCache: CityEntry[] | null = null;
let _discoveredCacheLoadedFor: R2Bucket | null = null;

export async function loadDiscoveredCities(
    env: Env,
): Promise<CityEntry[]> {
    if (
        _discoveredCache !== null &&
        _discoveredCacheLoadedFor === env.CACHE
    ) {
        return _discoveredCache;
    }
    try {
        const obj = await env.CACHE.get(DISCOVERED_R2_KEY);
        if (!obj) {
            _discoveredCache = [];
        } else {
            const parsed = (await obj.json()) as unknown;
            _discoveredCache = Array.isArray(parsed)
                ? (parsed as CityEntry[]).filter(
                      (e) =>
                          e &&
                          typeof e.relationId === "number" &&
                          typeof e.name === "string",
                  )
                : [];
        }
    } catch (e) {
        console.warn("loadDiscoveredCities failed:", e);
        _discoveredCache = [];
    }
    _discoveredCacheLoadedFor = env.CACHE;
    return _discoveredCache;
}

export async function getPopularCities(
    env: Env,
): Promise<CityEntry[]> {
    const growth = await loadDiscoveredCities(env);
    // TWO sources, clean roles (v680): the R2 growth/state doc FIRST (it
    // carries `extent` + curation stamps + player-added areas), then the
    // static SEED_CITIES (world-cities.json + overrides). mergeUnique is
    // first-wins-by-relationId with field-fill, so the growth doc's runtime
    // state wins while the seed supplies any city the growth doc lacks.
    return mergeUnique(growth, SEED_CITIES);
}

/**
 * Append newly discovered entries to the R2-stored list. Idempotent
 * via `mergeUnique` semantics; the cache is invalidated so the next
 * `getPopularCities(env)` call sees the updates.
 */
export async function appendDiscoveredCities(
    env: Env,
    fresh: CityEntry[],
): Promise<void> {
    if (fresh.length === 0) return;
    const existing = await loadDiscoveredCities(env);
    const merged = mergeUnique(existing, fresh);
    await env.CACHE.put(
        DISCOVERED_R2_KEY,
        JSON.stringify(merged),
        { httpMetadata: { contentType: "application/json" } },
    );
    _discoveredCache = merged;
    _discoveredCacheLoadedFor = env.CACHE;
}

/**
 * Remove a discovered entry by relation id. Used to evict entries
 * whose Photon-resolved relation turned out NOT to be an admin
 * boundary — their `relation(N);out geom;` fetch comes back empty,
 * so they fail every prewarm run. Removing them returns the name to
 * the unresolved queue, where the (now boundary-filtered) resolver
 * re-resolves it to the correct relation. Returns true if an entry
 * was actually removed. Only touches the discovered R2 doc; bundled
 * HAND_CURATED / BULK_CITIES entries are never evicted (they're not
 * in this doc).
 */
/**
 * Overwrite the whole discovered-cities R2 doc. Used by the
 * `/admin/rediscover` re-resolve pass, which rewrites existing entries'
 * relation ids in place after the resolver's re-rank fix. Keeps the
 * module cache in sync so the next read sees the update.
 */
export async function setDiscoveredCities(
    env: Env,
    list: CityEntry[],
): Promise<void> {
    await env.CACHE.put(DISCOVERED_R2_KEY, JSON.stringify(list), {
        httpMetadata: { contentType: "application/json" },
    });
    _discoveredCache = list;
    _discoveredCacheLoadedFor = env.CACHE;
}

export async function removeDiscoveredByRelationId(
    env: Env,
    relationId: number,
): Promise<boolean> {
    const existing = await loadDiscoveredCities(env);
    const next = existing.filter((c) => c.relationId !== relationId);
    if (next.length === existing.length) return false;
    await env.CACHE.put(DISCOVERED_R2_KEY, JSON.stringify(next), {
        httpMetadata: { contentType: "application/json" },
    });
    _discoveredCache = next;
    _discoveredCacheLoadedFor = env.CACHE;
    return true;
}

/**
 * Names of EVERY known city (bundled or discovered) that's missing
 * the `extent` field. The cron computes extents directly from the
 * known relationId via polygons.openstreetmap.fr — no Photon name
 * lookup, so it's immune to "Stockholm in Sweden vs Maine"
 * ambiguities. Returns at most `limit` entries with `{name, relationId}`.
 */
export async function missingExtentRelations(
    env: Env,
    limit: number,
): Promise<{ name: string; relationId: number }[]> {
    const all = await getPopularCities(env);
    const out: { name: string; relationId: number }[] = [];
    for (const c of all) {
        if (out.length >= limit) break;
        if (c.extent && c.extent.length === 4) continue;
        if (!Number.isFinite(c.relationId) || c.relationId <= 0) continue;
        out.push({ name: c.name, relationId: c.relationId });
    }
    return out;
}

/**
 * One-time-safe repair of the discovered-cities R2 doc: drop any
 * entry whose name (case-insensitive, comma-trimmed) collides with
 * the bundled HAND_CURATED or BULK_CITIES list but whose relationId
 * does NOT match the bundled canonical id. Those are the entries
 * left by an earlier bug where `resolveNameViaPhoton("Stockholm")`
 * resolved to Stockholm, Maine instead of Stockholm, Sweden.
 *
 * Returns the number of entries dropped. Idempotent — running it
 * again finds nothing to repair.
 */
export async function repairBogusDiscoveredEntries(
    env: Env,
): Promise<number> {
    const discovered = await loadDiscoveredCities(env);
    if (discovered.length === 0) return 0;
    const canonical = new Map<string, number>();
    const cityKey = (name: string) =>
        name.split(",")[0].trim().toLowerCase();
    for (const c of SEED_CITIES) {
        if (!canonical.has(cityKey(c.name))) {
            canonical.set(cityKey(c.name), c.relationId);
        }
    }
    const next = discovered.filter((c) => {
        const want = canonical.get(cityKey(c.name));
        if (want === undefined) return true; // not a bundled name
        return c.relationId === want; // keep only correct matches
    });
    const removed = discovered.length - next.length;
    if (removed === 0) return 0;
    await env.CACHE.put(
        DISCOVERED_R2_KEY,
        JSON.stringify(next),
        { httpMetadata: { contentType: "application/json" } },
    );
    _discoveredCache = next;
    _discoveredCacheLoadedFor = env.CACHE;
    return removed;
}

/** Upsert a city into the discovered list by relationId: overwrite the
 *  existing entry (preferring the new fields) or append if absent.
 *  Used by the backfill to add `extent` to legacy entries. */
export async function upsertDiscoveredCity(
    env: Env,
    entry: CityEntry,
): Promise<void> {
    const existing = await loadDiscoveredCities(env);
    let found = false;
    const next = existing.map((c) => {
        if (c.relationId === entry.relationId) {
            found = true;
            return { ...c, ...entry };
        }
        return c;
    });
    if (!found) next.push(entry);
    await env.CACHE.put(
        DISCOVERED_R2_KEY,
        JSON.stringify(next),
        { httpMetadata: { contentType: "application/json" } },
    );
    _discoveredCache = next;
    _discoveredCacheLoadedFor = env.CACHE;
}

/**
 * Bundled candidate city-name list (~600 entries). Used by the
 * discover pipeline as the source of names to resolve.
 */
export const CANDIDATE_NAMES: string[] = (
    BULK_CANDIDATE_NAMES as string[]
).filter((n) => typeof n === "string" && n.length > 0);

/**
 * R2 key under which Photon-resolution attempt counts accumulate,
 * keyed by lowercase head-name. A candidate that Photon can't resolve
 * (returns no relation) would otherwise sit at the front of the
 * unresolved queue forever — `unresolvedCandidates` only drops names
 * once they're KNOWN, and a failed name never becomes known. Every
 * discover call would re-attempt the same dead front names and never
 * reach the ones behind them, which is why the discovered list stalls.
 *
 * Parking failed names after MAX_DISCOVER_ATTEMPTS tries (so a
 * transient Photon blip gets a few chances first) lets the queue
 * advance past genuinely-unresolvable names. Clearable by deleting
 * this R2 object if a name should be retried from scratch.
 */
export const DISCOVER_ATTEMPTS_R2_KEY = "_meta/discover-attempts.json";
const MAX_DISCOVER_ATTEMPTS = 3;

let _attemptsCache: Record<string, number> | null = null;
let _attemptsCacheLoadedFor: R2Bucket | null = null;

async function loadDiscoverAttempts(
    env: Env,
): Promise<Record<string, number>> {
    if (_attemptsCache !== null && _attemptsCacheLoadedFor === env.CACHE) {
        return _attemptsCache;
    }
    try {
        const obj = await env.CACHE.get(DISCOVER_ATTEMPTS_R2_KEY);
        const parsed = obj ? ((await obj.json()) as unknown) : {};
        _attemptsCache =
            parsed && typeof parsed === "object" && !Array.isArray(parsed)
                ? (parsed as Record<string, number>)
                : {};
    } catch (e) {
        console.warn("loadDiscoverAttempts failed:", e);
        _attemptsCache = {};
    }
    _attemptsCacheLoadedFor = env.CACHE;
    return _attemptsCache;
}

/**
 * Park candidate names immediately (set their attempt count straight
 * to the max) so `unresolvedCandidates` stops returning them. Used
 * for names that DO resolve via Photon but to a relation id already
 * claimed by another entry — `appendDiscoveredCities` dedupes them
 * by relation id so they're never stored, their head never enters
 * the known set, and they'd otherwise loop forever (resolved every
 * call, never excluded). Parking ends the loop in one pass.
 */
export async function parkNames(
    env: Env,
    names: string[],
): Promise<void> {
    if (names.length === 0) return;
    const attempts = { ...(await loadDiscoverAttempts(env)) };
    for (const raw of names) {
        const head = raw.split(",")[0].trim().toLowerCase();
        if (!head) continue;
        attempts[head] = MAX_DISCOVER_ATTEMPTS;
    }
    await env.CACHE.put(DISCOVER_ATTEMPTS_R2_KEY, JSON.stringify(attempts), {
        httpMetadata: { contentType: "application/json" },
    });
    _attemptsCache = attempts;
    _attemptsCacheLoadedFor = env.CACHE;
}

/**
 * Record a failed Photon resolution for each of `names` (by lowercase
 * head-name), incrementing its attempt count. Once a name's count
 * reaches MAX_DISCOVER_ATTEMPTS, `unresolvedCandidates` stops
 * returning it and the queue advances.
 */
export async function recordFailedResolves(
    env: Env,
    names: string[],
): Promise<void> {
    if (names.length === 0) return;
    const attempts = { ...(await loadDiscoverAttempts(env)) };
    for (const raw of names) {
        const head = raw.split(",")[0].trim().toLowerCase();
        if (!head) continue;
        attempts[head] = (attempts[head] ?? 0) + 1;
    }
    await env.CACHE.put(DISCOVER_ATTEMPTS_R2_KEY, JSON.stringify(attempts), {
        httpMetadata: { contentType: "application/json" },
    });
    _attemptsCache = attempts;
    _attemptsCacheLoadedFor = env.CACHE;
}

/**
 * Names that haven't been resolved into a relation ID yet. Drops
 * anything whose name (case-insensitive substring match, before the
 * first comma) appears in the merged HAND_CURATED + BULK_CITIES +
 * R2-stored set, AND anything parked after MAX_DISCOVER_ATTEMPTS
 * failed Photon resolutions (see DISCOVER_ATTEMPTS_R2_KEY).
 */
export async function unresolvedCandidates(
    env: Env,
): Promise<string[]> {
    const known = await getPopularCities(env);
    // Compare HEAD-to-HEAD (the part before the first comma). The
    // candidate names carry a country qualifier ("Aarhus, Denmark")
    // and so do the discovered entries we store for them — but the
    // bundled HAND_CURATED / BULK_CITIES names are bare ("Aarhus").
    // The previous code matched the candidate's head against each
    // known entry's FULL name, so a discovered "Aarhus, Denmark"
    // never matched the candidate's head "aarhus" and the name was
    // re-resolved on every discover call forever — the front of the
    // queue jammed and the unresolved count never dropped (the
    // overnight laptop log showed 300 calls all "+25 resolved, 1257
    // unresolved"). Normalising both sides to the head fixes it.
    const knownHeads = new Set(
        known.map((c) => c.name.split(",")[0].trim().toLowerCase()),
    );
    const attempts = await loadDiscoverAttempts(env);
    return CANDIDATE_NAMES.filter((raw) => {
        const headLower = raw.split(",")[0].trim().toLowerCase();
        if (knownHeads.has(headLower)) return false;
        if ((attempts[headLower] ?? 0) >= MAX_DISCOVER_ATTEMPTS) return false;
        return true;
    });
}
