import { Download, RefreshCw } from "lucide-react";
import { useEffect, useRef, useState } from "react";
// vite-pwa virtual module — generated by the integration; the
// d.ts is shipped by the package so this works at typecheck
// time too (post-migration the @ts-expect-error is no longer
// needed because vite-plugin-pwa/client types are in tsconfig).
import { registerSW } from "virtual:pwa-register";

import { hidingPeriodEndsAt } from "@/lib/gameSetup";
import { currentGameCode } from "@/lib/multiplayer/session";
import { cn } from "@/lib/utils";

/**
 * PWA-update notifier + safe auto-updater (v930).
 *
 * The app runs in "prompt" registration mode (not autoUpdate), so a fresh
 * deploy's service worker WAITS instead of reloading the page from under
 * the user. This component decides when to swap:
 *
 *  - **Idle** (not in a multiplayer room AND no active game) → apply the
 *    update immediately (a reload), preserving the "auto-update on deploy"
 *    intent for users sitting on the landing / setup screens.
 *  - **In a lobby or live game** → do NOT reload out from under them; show
 *    a "Reload to update" prompt and auto-apply the moment they become
 *    idle (leave the room / round ends). This fixes the "reload out of
 *    nowhere threw me out of the lobby" bug.
 *
 * Mount once near the root — render-yields `null` when no update is
 * pending, so it stays out of the way.
 */
function isSafeToReload(): boolean {
    // Safe to hard-reload only when the user isn't in a shared room and no
    // game clock is running (lobby membership rides `currentGameCode`).
    return (
        currentGameCode.get() === null && hidingPeriodEndsAt.get() === null
    );
}

export function PWAUpdatePrompt() {
    const [needRefresh, setNeedRefresh] = useState(false);
    const [updateSW, setUpdateSW] = useState<
        ((reloadPage?: boolean) => Promise<void>) | null
    >(null);
    const updateRef = useRef<
        ((reloadPage?: boolean) => Promise<void>) | null
    >(null);

    useEffect(() => {
        // `registerSW` returns the update function. Pass callbacks
        // so React state flips when the SW lifecycle reports
        // `needRefresh` or `offlineReady`.
        //
        // We also actively poll for updates: vite-plugin-pwa only
        // checks once at registration by default, so a tab that
        // stays open for hours never picks up a new build. We poll
        // every 60 s while the tab is visible, plus on every focus,
        // so the user sees the "Update ready" prompt within a
        // minute of a deploy instead of after a manual reload.
        let pollTimer: number | null = null;
        let focusHandler: (() => void) | null = null;
        try {
            const update = registerSW({
                immediate: true,
                onNeedRefresh() {
                    // A new SW is waiting. Apply immediately only if it's
                    // safe (idle); otherwise defer — surface the prompt and
                    // let the idle-watcher effect apply it later so we never
                    // reload a live lobby/game.
                    if (isSafeToReload()) {
                        updateRef.current?.(true);
                    } else {
                        setNeedRefresh(true);
                    }
                },
                onOfflineReady() {
                    // We don't toast this — the SW becoming ready is
                    // an implementation detail; the user will notice
                    // when they actually go offline.
                },
                onRegisterError(error: unknown) {
                    console.warn("PWA SW register error", error);
                },
                onRegisteredSW(_swUrl, registration) {
                    if (!registration) return;
                    const checkForUpdate = () => {
                        // `update()` is fire-and-forget. If a new SW
                        // is available, the registration lifecycle
                        // fires our onNeedRefresh callback above.
                        registration.update().catch(() => {
                            /* offline, transient — try again next tick */
                        });
                    };
                    pollTimer = window.setInterval(checkForUpdate, 60_000);
                    focusHandler = () => {
                        if (document.visibilityState === "visible") {
                            checkForUpdate();
                        }
                    };
                    document.addEventListener(
                        "visibilitychange",
                        focusHandler,
                    );
                },
            });
            updateRef.current = update;
            setUpdateSW(() => update);
        } catch (e) {
            // `registerSW` is a no-op outside of a service-worker-
            // capable environment (e.g. some embedded browsers).
            console.warn("PWA registration failed", e);
        }

        return () => {
            if (pollTimer !== null) window.clearInterval(pollTimer);
            if (focusHandler !== null) {
                document.removeEventListener(
                    "visibilitychange",
                    focusHandler,
                );
            }
        };
    }, []);

    // A deferred update is pending: auto-apply the moment the user becomes
    // idle (leaves the room / the game clock clears), so we still get
    // auto-update-on-deploy without ever reloading a live lobby/game.
    useEffect(() => {
        if (!needRefresh) return;
        const maybeApply = () => {
            if (isSafeToReload()) updateRef.current?.(true);
        };
        maybeApply();
        const unsubCode = currentGameCode.subscribe(maybeApply);
        const unsubClock = hidingPeriodEndsAt.subscribe(maybeApply);
        return () => {
            unsubCode();
            unsubClock();
        };
    }, [needRefresh]);

    if (!needRefresh) return null;

    return (
        <div
            className={cn(
                "fixed left-3 right-3 z-[1060]",
                "bottom-[calc(96px+env(safe-area-inset-bottom))] md:bottom-4 md:right-4 md:left-auto md:max-w-sm",
                "rounded-md border-2 border-primary",
                "bg-background/95 backdrop-blur-md shadow-2xl",
                "px-3 py-3",
            )}
            role="status"
            aria-live="polite"
        >
            <div className="flex items-start gap-3">
                <Download className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <div className="min-w-0 flex-1">
                    <div className="text-xs font-poppins font-bold uppercase tracking-[0.14em] text-primary">
                        Update ready
                    </div>
                    <p className="text-xs text-muted-foreground leading-snug mt-0.5">
                        A new version of the app is cached and ready
                        to take over.
                    </p>
                </div>
            </div>
            <div className="mt-2.5 flex gap-2">
                <button
                    type="button"
                    onClick={() => setNeedRefresh(false)}
                    className={cn(
                        "flex-1 px-2.5 py-1.5 rounded-sm text-xs font-poppins font-semibold",
                        "bg-secondary text-foreground hover:bg-accent border border-border",
                        "transition-colors",
                    )}
                >
                    Later
                </button>
                <button
                    type="button"
                    onClick={() => updateSW?.(true)}
                    className={cn(
                        "flex-1 px-2.5 py-1.5 rounded-sm text-xs font-poppins font-bold",
                        "bg-primary text-primary-foreground hover:bg-primary/90",
                        "transition-colors gap-1.5 flex items-center justify-center",
                    )}
                >
                    <RefreshCw className="w-3 h-3" />
                    Reload to update
                </button>
            </div>
        </div>
    );
}

export default PWAUpdatePrompt;
