import { Download, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
// vite-pwa virtual module — generated by the integration; the
// d.ts is shipped by the package so this works at typecheck
// time too (post-migration the @ts-expect-error is no longer
// needed because vite-plugin-pwa/client types are in tsconfig).
import { registerSW } from "virtual:pwa-register";

import { cn } from "@/lib/utils";

/**
 * Floating PWA-update notifier. Becomes visible only after `vite-pwa`
 * detects a new service-worker waiting to take over. The seeker
 * taps "Reload" to apply it immediately; otherwise the autoUpdate
 * policy will swap on the next cold page load anyway, so dismissing
 * is fine.
 *
 * Mount once near the root (Layout) — render-yields `null` when no
 * update is pending, so it stays out of the way.
 */
export function PWAUpdatePrompt() {
    const [needRefresh, setNeedRefresh] = useState(false);
    const [updateSW, setUpdateSW] = useState<
        ((reloadPage?: boolean) => Promise<void>) | null
    >(null);

    useEffect(() => {
        // `registerSW` returns the update function. Pass callbacks
        // so React state flips when the SW lifecycle reports
        // `needRefresh` or `offlineReady`.
        try {
            const update = registerSW({
                immediate: true,
                onNeedRefresh() {
                    setNeedRefresh(true);
                },
                onOfflineReady() {
                    // We don't toast this — the SW becoming ready is
                    // an implementation detail; the user will notice
                    // when they actually go offline.
                },
                onRegisterError(error: unknown) {
                    console.warn("PWA SW register error", error);
                },
            });
            setUpdateSW(() => update);
        } catch (e) {
            // `registerSW` is a no-op outside of a service-worker-
            // capable environment (e.g. some embedded browsers).
            console.warn("PWA registration failed", e);
        }
    }, []);

    if (!needRefresh) return null;

    return (
        <div
            className={cn(
                "fixed left-3 right-3 z-[1060]",
                "bottom-[calc(96px+env(safe-area-inset-bottom))] md:bottom-4 md:right-4 md:left-auto md:max-w-sm",
                "rounded-md border-2 border-primary",
                "bg-background/95 backdrop-blur-md shadow-2xl",
                "px-3 py-3",
            )}
            role="status"
            aria-live="polite"
        >
            <div className="flex items-start gap-3">
                <Download className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <div className="min-w-0 flex-1">
                    <div className="text-xs font-poppins font-bold uppercase tracking-[0.14em] text-primary">
                        Update ready
                    </div>
                    <p className="text-xs text-muted-foreground leading-snug mt-0.5">
                        A new version of the app is cached and ready
                        to take over.
                    </p>
                </div>
            </div>
            <div className="mt-2.5 flex gap-2">
                <button
                    type="button"
                    onClick={() => setNeedRefresh(false)}
                    className={cn(
                        "flex-1 px-2.5 py-1.5 rounded-sm text-xs font-poppins font-semibold",
                        "bg-secondary text-foreground hover:bg-accent border border-border",
                        "transition-colors",
                    )}
                >
                    Later
                </button>
                <button
                    type="button"
                    onClick={() => updateSW?.(true)}
                    className={cn(
                        "flex-1 px-2.5 py-1.5 rounded-sm text-xs font-poppins font-bold",
                        "bg-primary text-primary-foreground hover:bg-primary/90",
                        "transition-colors gap-1.5 flex items-center justify-center",
                    )}
                >
                    <RefreshCw className="w-3 h-3" />
                    Reload to update
                </button>
            </div>
        </div>
    );
}

export default PWAUpdatePrompt;
